### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by dushlev** [dushlev/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by anatolii-dyshlevskyi** [comment]
His parents sent young Donald to the New York Military Academy at 13 years old. It’s said that the academy could be a brutal place where threats and force were used to keep order.
By the time Trump was 27, he had already owned 14,000 apartments and was running the Trump Management Corporation.
As of September 2019, Donald Trump reportedly had a total net worth of $3.1 billion.
Donald Trump loves to drink Diet Coke. It’s reported that he drinks roughly 12 cans of Diet Coke per day… that’s a lot of soda! He’s also a huge fan of fast food such as McDonald’s, Burger King, and KFC. He loves McDonald’s so much, that he’s even asked the White House to recreate the food!
